-- 1. 急診檢驗檢查主檔
CREATE TABLE DB_ADM_ORDER_ER (
    CHAD1CASENO     VARCHAR(11) NOT NULL,
    CHAD1MRNO       VARCHAR(10) NOT NULL,
    CHAD4GREQNO     NUMERIC NULL,
    CHAD4CDATE      VARCHAR(12) NULL,
    CHAD1ORDNO      VARCHAR(10) NOT NULL,
    CHAD4ORDNAME    VARCHAR(175) NULL,
    CHTEAMNAM       VARCHAR(2) NOT NULL,
    CHAD4SPECT      VARCHAR(30) NULL,
    CHAD4DCDATE      CHAR(1) NULL,
    CHAD4STAT       VARCHAR(2) NULL,
    CHAD4REP1       CHAR(1) NULL,
    CHRCPDTM        VARCHAR(12) NULL,
    CHREPORTDATE    VARCHAR(12) NULL,
    CHTEXT          TEXT NULL,
    SOURCETYPE      CHAR(1) NULL
);

-- 2. 急診檢驗頭檔
CREATE TABLE DB_ADM_LABORDER_ER (
    CHCASENO    VARCHAR(11) NOT NULL,
    CHMRNO      VARCHAR(10) NOT NULL,
    CHGREQNO    NUMERIC NULL,
    CHAPPDTM    VARCHAR(12) NULL,
    CHLREQNO    VARCHAR(2) NULL,
    CHORDNO     VARCHAR(10) NULL,
    CHORDNAM    VARCHAR(60) NOT NULL,
    CHTEAMNAM   VARCHAR(2) NULL,
    CHSTAT      NUMERIC NULL,
    CHSPECI     VARCHAR(30) NULL,
    SOURCETYPE  CHAR(1) NULL,
    ORDSEQ      VARCHAR(27) NULL,
    CHTAPPDT    VARCHAR(8) NOT NULL,
    CHRCPDTM    VARCHAR(12) NULL,
    CHRCONNAME  VARCHAR(40) NULL,
    CONCODE     VARCHAR(2) NULL,
    LABMCHNO    INTEGER NOT NULL,
    LABUNIFNO   INTEGER NULL,
    LABCLASS    VARCHAR(2) NOT NULL,
    ORDPROCDTTM VARCHAR(14) NOT NULL
);

-- 3. 急診檢驗明細
CREATE TABLE DB_ADM_LABDATA_ER (
    CHAD1CASENO     VARCHAR(11) NOT NULL,
    CHMRNO          VARCHAR(10) NOT NULL,
    CHGREQNO        INTEGER NOT NULL,
    CHAPPDTM        VARCHAR(12) NULL,
    CHRCPDTM        VARCHAR(12) NULL,
    CHLREQNO        VARCHAR(2) NOT NULL,
    CHORDNO         VARCHAR(10) NOT NULL,
    CHITEMNO        VARCHAR(50) NULL,
    CHHEAD          VARCHAR(175) NULL,
    CHTEAMNAM       VARCHAR(2) NOT NULL,
    CHSTAT          NUMERIC NULL,
    CHSPECI         VARCHAR(30) NULL,
    CHVAL           VARCHAR(250) NULL,
    CHUNIT          VARCHAR(10) NULL,
    CHCOMMT         VARCHAR(255) NULL, -- PostgreSQL 不支援 CHAR(0)，改為 VARCHAR
    CHNL            VARCHAR(16) NULL,
    CHNH            VARCHAR(16) NULL,
    CHITEMSEQ       INTEGER NULL,
    CHREPORTDATE    VARCHAR(12) NULL,
    CHTEXT          TEXT NULL,
    CHSIGNDTTM      VARCHAR(12) NULL,
    CHLABAPCODE     VARCHAR(8) NULL
);

-- 4. 急診護理紀錄
CREATE TABLE ENSDATA (
    TRINO       VARCHAR(11) NOT NULL,
    PATID       VARCHAR(10) NOT NULL,
    VISITDT     VARCHAR(8) NOT NULL,
    SEQ         INTEGER NOT NULL,
    SUBJECT     TEXT NOT NULL,
    PROCDTTM    VARCHAR(14) NULL,
    DIAGNOSIS   TEXT NULL,
    CLOSE       VARCHAR(1) NULL,
    FIINISH     CHAR(1) NULL
);

-- 5. 急診生理監測
CREATE TABLE v_ai_hisensnes (
    TRINO       VARCHAR(12) NOT NULL,
    PATID       VARCHAR(10) NOT NULL,
    VISITDT     VARCHAR(8) NOT NULL,
    EWEIGHT     VARCHAR(6) NOT NULL,
    ETEMPUTER   VARCHAR(6) NOT NULL,
    ETREGION    VARCHAR(1) NOT NULL,
    EPLUSE      VARCHAR(3) NOT NULL,
    EBREATHE    VARCHAR(3) NOT NULL,
    EPRESSURE   VARCHAR(3) NOT NULL,
    EDIASTOLIC  VARCHAR(3) NOT NULL,
    ESAO2       VARCHAR(10) NOT NULL,
    GCS_E       VARCHAR(10) NOT NULL,
    GCS_V       VARCHAR(10) NOT NULL,
    GCS_M       VARCHAR(10) NOT NULL,
    PUPIL_L     VARCHAR(10) NOT NULL,
    PUPIL_R     VARCHAR(10) NOT NULL,
    ENESKIND    VARCHAR(1) NOT NULL,
    PROCDTTM    VARCHAR(14) NOT NULL
);